name: modal_progress_hud
description: A modal progress indicator widget (HUD = heads-up display). Wrap
  around another widget to block access to widget during an async call. Also
  accepts a custom spinner.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: null
